# Generated by Django 4.2.7 on 2026-08-18 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('acreage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('soil_type', models.CharField(choices=[('CLAY', 'Clay'), ('LOAM', 'Loam'), ('SANDY', 'Sandy'), ('SILT', 'Silt'), ('PEATY', 'Peaty'), ('CHALKY', 'Chalky')], default='LOAM', max_length=20)),
                ('gps_coordinates', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='accounts.farmprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LandParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_type', models.CharField(choices=[('OWNED', 'Owned'), ('LEASED', 'Leased'), ('RENTED', 'Rented')], default='OWNED', max_length=20)),
                ('lease_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lease_start', models.DateField(blank=True, null=True)),
                ('lease_end', models.DateField(blank=True, null=True)),
                ('owner_name', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='fields.field')),
            ],
        ),
    ]
