# Generated by Django 4.2.7 on 2026-08-19 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('scientific_name', models.CharField(blank=True, default='', max_length=200)),
                ('category', models.CharField(choices=[('GRAIN', 'Grain'), ('OILSEED', 'Oilseed'), ('FORAGE', 'Forage'), ('VEGETABLE', 'Vegetable'), ('FRUIT', 'Fruit'), ('ROOT', 'Root/Tuber'), ('LEGUME', 'Legume'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('default_unit', models.CharField(default='kg', max_length=20)),
                ('growing_season_days', models.PositiveIntegerField(blank=True, default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='cropseason',
            name='crop_type',
        ),
        migrations.AddField(
            model_name='cropseason',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seasons', to='crops.crop'),
        ),
    ]
