# Generated by Django 4.2.7 on 2026-08-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_crop_model_and_crop_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='harvest_frequency',
            field=models.CharField(blank=True, default='', help_text='How often it is harvested, e.g. "Annual", "Biannual", "Every 3 months".', max_length=50),
        ),
        migrations.AddField(
            model_name='crop',
            name='is_perennial',
            field=models.BooleanField(default=False, help_text='Perennial crops are planted once and harvested seasonally over many years (e.g. coffee, tea, fruit trees).'),
        ),
        migrations.AddField(
            model_name='crop',
            name='perennial_lifespan_years',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Expected productive lifespan in years (for perennial crops).'),
        ),
        migrations.AddField(
            model_name='cropseason',
            name='is_perennial_season',
            field=models.BooleanField(default=False, help_text='Check if this is a seasonal harvest cycle of a perennial crop (e.g. coffee harvest season).'),
        ),
        migrations.AddField(
            model_name='cropseason',
            name='perennial_established_date',
            field=models.DateField(blank=True, help_text='When the perennial crop was originally planted (for multi-year crops).', null=True),
        ),
        migrations.AddField(
            model_name='cropseason',
            name='season_label',
            field=models.CharField(blank=True, default='', help_text='Label for perennial harvest cycles, e.g. "2025 Main Harvest", "2025 Fly Crop".', max_length=100),
        ),
        migrations.AddField(
            model_name='harvestrecord',
            name='harvest_type',
            field=models.CharField(choices=[('MAIN', 'Main Harvest'), ('SECONDARY', 'Secondary Harvest'), ('THINNING', 'Thinning'), ('GLEANING', 'Gleaning')], default='MAIN', max_length=20),
        ),
        migrations.AddField(
            model_name='harvestrecord',
            name='moisture_content',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Percentage moisture content', max_digits=5),
        ),
        migrations.AddField(
            model_name='harvestrecord',
            name='quality_grade',
            field=models.CharField(blank=True, default='', help_text='e.g. Grade A, Premium, Standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='crop',
            name='category',
            field=models.CharField(choices=[('GRAIN', 'Grain'), ('OILSEED', 'Oilseed'), ('FORAGE', 'Forage'), ('VEGETABLE', 'Vegetable'), ('FRUIT', 'Fruit'), ('ROOT', 'Root/Tuber'), ('LEGUME', 'Legume'), ('BEVERAGE', 'Beverage (Coffee/Tea)'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='cropseason',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('PLANTED', 'Planted'), ('GROWING', 'Growing'), ('FLOWERING', 'Flowering'), ('HARVESTED', 'Harvested'), ('DORMANT', 'Dormant'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20),
        ),
    ]
