# Generated by Django 4.2.7 on 2026-08-24 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0003_crop_harvest_frequency_crop_is_perennial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('added_value', models.DecimalField(decimal_places=2, default=0, help_text='Additional value created at this stage.', max_digits=12)),
                ('output_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('output_unit', models.CharField(blank=True, default='', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('harvest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_stages', to='crops.harvestrecord')),
            ],
            options={
                'ordering': ['harvest', 'sequence'],
            },
        ),
    ]
