# Generated by Django 4.2.7 on 2026-08-24 11:44

from django.db import migrations, models
import django.db.models.deletion


def move_harvest_prices_to_sales(apps, schema_editor):
    HarvestRecord = apps.get_model('crops', 'HarvestRecord')
    Sale = apps.get_model('crops', 'Sale')
    for harvest in HarvestRecord.objects.all():
        if harvest.market_price:
            Sale.objects.create(
                harvest=harvest,
                sale_date=harvest.harvest_date,
                quantity=harvest.quantity,
                unit=harvest.unit,
                unit_price=harvest.market_price,
                buyer=harvest.buyer,
            )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0004_processingstage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('buyer', models.CharField(blank=True, default='', max_length=200)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('MOBILE', 'Mobile Money'), ('CREDIT', 'Credit'), ('OTHER', 'Other')], default='CASH', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('harvest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='crops.harvestrecord')),
                ('processing_stage', models.ForeignKey(blank=True, help_text='Set if the produce sold came out of a specific processing stage.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='crops.processingstage')),
            ],
            options={
                'ordering': ['-sale_date', '-id'],
            },
        ),
        migrations.RunPython(move_harvest_prices_to_sales, noop),
        migrations.RemoveField(
            model_name='harvestrecord',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='harvestrecord',
            name='market_price',
        ),
        migrations.AlterField(
            model_name='harvestrecord',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Quantity harvested (not sold).', max_digits=12),
        ),
    ]
