# Generated by Django 4.2.7 on 2026-08-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0005_remove_harvestrecord_buyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='secondary_unit',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='processingstage',
            name='input_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Quantity of raw produce used in this stage.', max_digits=12),
        ),
    ]
