# Generated by Django 4.2.7 on 2026-08-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0006_crop_secondary_unit_processingstage_input_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingstage',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of days the stage is expected to take.'),
        ),
        migrations.AddField(
            model_name='processingstage',
            name='start_date',
            field=models.DateField(blank=True, help_text='Date processing for this stage begins.', null=True),
        ),
    ]
