# Generated by Django 4.2.7 on 2026-08-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0007_processingstage_duration_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='secondary_per_primary',
            field=models.DecimalField(blank=True, decimal_places=4, default=1, help_text='How many secondary units make up one primary unit (e.g., 1000 if 1 kg = 1000 g).', max_digits=14),
        ),
    ]
