# Generated by Django 4.2.7 on 2026-08-27 11:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0008_crop_secondary_per_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestrecord',
            name='waste_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Quantity of waste produced during harvest.', max_digits=12),
        ),
        migrations.AddField(
            model_name='harvestrecord',
            name='waste_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Estimated value or loss of the waste.', max_digits=12),
        ),
        migrations.AddField(
            model_name='processingstage',
            name='waste_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Quantity of waste produced during processing.', max_digits=12),
        ),
        migrations.AddField(
            model_name='processingstage',
            name='waste_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Estimated value or loss of the waste.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='crop',
            name='secondary_per_primary',
            field=models.DecimalField(blank=True, decimal_places=4, default=1, help_text='How many primary units make up one secondary unit (e.g., 100 if 1 bag = 100 kg).', max_digits=14),
        ),
    ]
