# Generated by Django 4.2.7 on 2026-08-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0009_harvestrecord_waste_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestrecord',
            name='waste_name',
            field=models.CharField(blank=True, default='', help_text='Name/type of waste produced (e.g., husk, bran).', max_length=100),
        ),
        migrations.AddField(
            model_name='processingstage',
            name='waste_name',
            field=models.CharField(blank=True, default='', help_text='Name/type of waste produced (e.g., husk, bran).', max_length=100),
        ),
    ]
