# Generated by Django 4.2.7 on 2026-08-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0010_harvestrecord_waste_name_processingstage_waste_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_waste',
            field=models.BooleanField(default=False, help_text='Check if this sale is for waste material from the harvest or stage.'),
        ),
    ]
