# Generated by Django 4.2.7 on 2026-08-18 09:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
        ('equipment', '0001_initial'),
        ('accounts', '0001_initial'),
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('schedule_f_line', models.CharField(choices=[('part1_cartruck', 'Car and truck expenses'), ('part1_chemicals', 'Chemicals'), ('part1_conservation', 'Conservation expenses'), ('part1_custom_hire', 'Custom hire (machine work)'), ('part1_depreciation', 'Depreciation'), ('part1_employee_benefits', 'Employee benefit programs'), ('part1_feed', 'Feed'), ('part1_fertilizer', 'Fertilizer and lime'), ('part1_freight_trucking', 'Freight and trucking'), ('part1_gasoline_fuel', 'Gasoline, fuel, and oil'), ('part1_insurance', 'Insurance (other than health)'), ('part1_interest', 'Interest'), ('part1_labor_hired', 'Labor hired (less employment credits)'), ('part1_pension', 'Pension and profit-sharing plans'), ('part1_rent_lease_equipment', 'Rent or lease vehicles, machinery, equipment'), ('part1_rent_lease_land', 'Rent or lease land, animals'), ('part1_repairs_maintenance', 'Repairs and maintenance'), ('part1_seeds_plants', 'Seeds and plants'), ('part1_storage_warehousing', 'Storage and warehousing'), ('part1_supplies', 'Supplies purchased'), ('part1_taxes', 'Taxes'), ('part1_utilities', 'Utilities'), ('part1_veterinary', 'Veterinary, breeding, and medicine'), ('part1_other', 'Other or unspecified')], default='part1_other', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('vendor', models.CharField(blank=True, default='', max_length=200)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CHECK', 'Check'), ('CARD', 'Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('OTHER', 'Other')], default='CASH', max_length=20)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('notes', models.TextField(blank=True, default='')),
                ('reconciliation_status', models.CharField(choices=[('PENDING', 'Pending'), ('MATCHED', 'Matched'), ('RECONCILED', 'Reconciled'), ('FLAGGED', 'Flagged')], default='PENDING', max_length=20)),
                ('offline_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.category')),
                ('crop_season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='crops.cropseason')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='equipment.equipment')),
                ('farm_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='accounts.farmprofile')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='fields.field')),
            ],
        ),
    ]
