# Generated by Django 4.2.7 on 2026-08-18 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='budget',
            field=models.ForeignKey(blank=True, help_text='Every expense must be linked to a budget.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='budgets.budget'),
        ),
    ]
