# Generated by Django 4.2.7 on 2026-08-18 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_alter_budget_unique_together_budget_end_date_and_more'),
        ('expenses', '0002_expense_budget_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='budget',
        ),
        migrations.AddField(
            model_name='expense',
            name='budget_item',
            field=models.ForeignKey(blank=True, help_text='Every expense must be linked to a budget item.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='budgets.budgetitem'),
        ),
    ]
