# Generated by Django 4.2.7 on 2026-08-19 21:03

from django.db import migrations, models


def populate_unique_codes(apps, schema_editor):
    Category = apps.get_model('expenses', 'Category')
    for i, cat in enumerate(Category.objects.all().order_by('id'), start=1):
        cat.code = str(i * 100)
        cat.save(update_fields=['code'])


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_expense_budget_item_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, default='', help_text='Short code identifying this fund pool (e.g. 100, 200).', max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='fund_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total money available in this fund pool.', max_digits=12),
        ),
        migrations.RunPython(populate_unique_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, default='', help_text='Short code identifying this fund pool (e.g. 100, 200).', max_length=20, unique=True),
        ),
    ]
