# Generated by Django 4.2.7 on 2026-08-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_category_code_category_fund_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Budget Code', 'verbose_name_plural': 'Budget Codes'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='fund_amount',
        ),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, default='', help_text='Short code identifying this budget code (e.g. 100, 200).', max_length=20, unique=True),
        ),
    ]
