# Generated by Django 4.2.7 on 2026-08-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmprofile',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='farmprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='farm_logos/'),
        ),
        migrations.AddField(
            model_name='farmprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
