# Generated by Django 4.2.7 on 2026-08-26 05:06

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_farmprofile_email_farmprofile_logo_farmprofile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. USD, EUR, UGX', max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(default='$', max_length=10)),
                ('rate', models.DecimalField(decimal_places=6, default=Decimal('1.0'), help_text='Amount of this currency equal to 1 base (USD) unit', max_digits=18)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'currencies',
            },
        ),
        migrations.AddField(
            model_name='farmprofile',
            name='default_currency',
            field=models.ForeignKey(blank=True, help_text='Currency used to display monetary values', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farm_profiles', to='accounts.currency'),
        ),
    ]
