# Generated by Django 4.2.7 on 2026-08-18 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='expenses.category')),
                ('crop_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='crops.cropseason')),
            ],
            options={
                'unique_together': {('crop_season', 'category')},
            },
        ),
    ]
