# Generated by Django 4.2.7 on 2026-08-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_budget_crop_season_to_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='fund_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total money available for this code in this budget.', max_digits=12),
        ),
    ]
